const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('assets/site.js','utf8');
const css=fs.readFileSync('assets/site.css','utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);
assert.equal(new Set(ids).size,ids.length,'Duplicate ids');
for(const m of html.matchAll(/href="#([^"]+)"/g))assert(ids.includes(m[1]),'Missing anchor '+m[1]);
assert.equal((html.match(/<h1>/g)||[]).length,1,'Exactly one h1');
for(const file of ['favicon.svg','assets/og-cover.png','robots.txt','sitemap.xml','assets/site.css','assets/site.js'])assert(fs.existsSync(file),file);
assert(html.includes('Content-Security-Policy'));
assert(html.includes('https://t.me/Mary_Romanova_tg'));
assert(html.includes('https://wa.me/79687135343'));
assert(!js.includes('innerHTML'));
assert(!js.includes('localStorage'));
assert(!js.includes("'Выбран файл:'"),'Do not expose filename');
assert(js.includes("goal('sts_file_valid')"));
assert(!js.includes("addEventListener('click',()=>goal('sts"),'Do not count file dialog open');
assert(css.includes('@media(max-width:700px)'));
const handlers={};
const els={year:{textContent:''},structuredData:{textContent:''},stsFile:{files:[],value:'',addEventListener:(k,f)=>handlers[k]=f},fileTitle:{textContent:''},fileStatus:{textContent:''}};
const document={getElementById:id=>els[id]||null,querySelectorAll:()=>[{dataset:{goal:'telegram_click'},addEventListener(){}}],createElement:()=>({}),getElementsByTagName:()=>[{parentNode:{insertBefore(){}}}]};
vm.runInNewContext(js,{document,window:{ym(){}},Date});
els.stsFile.files=[{name:'sts.pdf',size:1024}];handlers.change();
assert.equal(els.fileTitle.textContent,'СТС выбран');
assert(els.fileStatus.textContent.includes('Файл подходит'));
els.stsFile.files=[{name:'virus.exe',size:1024}];handlers.change();
assert(els.fileStatus.textContent.includes('JPG, PNG или PDF'));
els.stsFile.files=[{name:'huge.pdf',size:11*1024*1024}];handlers.change();
assert(els.fileStatus.textContent.includes('до 10 МБ'));
assert(fs.readFileSync('robots.txt','utf8').includes('Sitemap: https://routemsk.ru/sitemap.xml'));
console.log('PASS: structure, anchors, contacts, CSP, privacy, analytics, file validation, mobile CSS, SEO assets');
